name: arch_practice
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # Provider for state management
  provider: ^6.0.4
  # Bloc for state management
  flutter_bloc: ^8.1.1
  bloc_test: ^9.1.0
  # Value equality
  equatable: ^2.0.5
  # Remote API
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  # Navigation
  flow_builder: ^0.0.9
  # Configuration
  global_configuration: ^2.0.0-nullsafety.1
  # UI
  flutter_staggered_grid_view: ^0.6.2
  cupertino_icons: ^1.0.2

  practice_api:
    path: ./packages/practice_api
  practice_repositories:
    path: ./packages/practice_repositories

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - config/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf
        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
        - asset: fonts/Montserrat/Montserrat-Light.ttf
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf